- name: Add deadsnake ppa.
  ansible.builtin.apt_repository:

    repo: ppa:deadsnakes/ppa
  become: true

- name: Install Pythons.
  ansible.builtin.apt:
    name:
      - python3.7
      - python3.8
      - python3.9
      - python3.10
      - python3.11
      - python3.12
      - python3.7-venv
      - python3.8-venv
      - python3.9-venv
      - python3.10-venv
      - python3.11-venv
      - python3.12-venv
  become: true
